#!/usr/bin/env bash
set -euo pipefail

# ╔══════════════════════════════════════════════════════════════════════╗
# ║  Update Local Models Registry                                       ║
# ║  Checks fastembed crate for new embedding models.                   ║
# ╚══════════════════════════════════════════════════════════════════════╝
#
# Usage:
#   bash scripts/update-local-models.sh          # check only (dry run)
#   bash scripts/update-local-models.sh --apply  # apply changes
#   bash scripts/update-local-models.sh --pr     # apply + open PR

APPLY=false
OPEN_PR=false
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGISTRY_FILE="${REPO_ROOT}/models/local-models.toml"
CARGO_TOML="${REPO_ROOT}/Cargo.toml"

for arg in "$@"; do
    case "$arg" in
        --apply) APPLY=true ;;
        --pr) APPLY=true; OPEN_PR=true ;;
        --help) echo "Usage: $0 [--apply] [--pr]"; exit 0 ;;
    esac
done

echo "═══ Local Models Registry Update ═══"
echo ""

# ── Step 1: Check current fastembed version ────────────────────────────
current_version=$(grep 'fastembed = ' "$CARGO_TOML" | head -1 | grep -oP '"\K[^"]+')
echo "Current fastembed version: ${current_version}"

# ── Step 2: Check latest fastembed version on crates.io ────────────────
echo "Checking crates.io for latest fastembed..."
latest_info=$(curl -sL "https://crates.io/api/v1/crates/fastembed" 2>/dev/null || echo "")

if [ -z "$latest_info" ]; then
    echo "WARNING: Could not reach crates.io. Skipping version check."
    latest_version="unknown"
else
    latest_version=$(echo "$latest_info" | python3 -c "
import json, sys
data = json.load(sys.stdin)
print(data.get('crate', {}).get('max_stable_version', 'unknown'))
" 2>/dev/null || echo "unknown")
fi

echo "Latest fastembed version: ${latest_version}"
echo ""

if [ "$latest_version" = "unknown" ]; then
    echo "Could not determine latest version. Manual check required."
    echo "Visit: https://crates.io/crates/fastembed"
    exit 0
fi

# ── Step 3: Compare versions ───────────────────────────────────────────
current_major=$(echo "$current_version" | grep -oP '^\d+')
latest_major=$(echo "$latest_version" | grep -oP '^\d+')

if [ "$current_major" = "$latest_major" ]; then
    echo "Major version matches (${current_major}). Minor/patch updates may add models."
else
    echo "NEW MAJOR VERSION: ${current_version} → ${latest_version}"
    echo "This likely includes new models. Review the changelog:"
    echo "  https://github.com/Anush008/fastembed-rs/releases"
fi

# ── Step 4: List current registry models ───────────────────────────────
echo ""
echo "Current registry models:"
grep '^\[models\.' "$REGISTRY_FILE" | sed 's/\[models\.\(.*\)\]/  - \1/' | sort
echo ""
model_count=$(grep -c '^\[models\.' "$REGISTRY_FILE")
echo "Total: ${model_count} models"

# ── Step 5: Report ─────────────────────────────────────────────────────
echo ""
echo "═══ Action Items ═══"
if [ "$current_major" != "$latest_major" ]; then
    echo "1. Review fastembed ${latest_version} changelog for new EmbeddingModel variants"
    echo "2. Add new models to models/local-models.toml with status = \"new\""
    echo "3. Add match arms to crates/the-one-memory/src/embeddings.rs enum_from_name()"
    echo "4. Run: cargo test -p the-one-memory"
    echo "5. Mark deprecated models with deprecated = true (do NOT remove)"
else
    echo "No major version change detected. Check minor release notes for new models."
fi

if [ "$APPLY" = true ]; then
    echo ""
    echo "═══ Applying Changes ═══"
    sed -i "s/^updated = .*/updated = \"$(date +%Y-%m-%d)\"/" "$REGISTRY_FILE"
    echo "Updated registry timestamp."

    if [ "$current_major" != "$latest_major" ]; then
        echo "Bumping fastembed version in Cargo.toml..."
        sed -i "s/fastembed = \"${current_version}\"/fastembed = \"${latest_major}\"/" "$CARGO_TOML"
        echo "Updated to fastembed = \"${latest_major}\""
        echo ""
        echo "NOTE: You must manually:"
        echo "  1. cargo update -p fastembed"
        echo "  2. Check for new EmbeddingModel enum variants"
        echo "  3. Add them to local-models.toml and embeddings.rs"
        echo "  4. Run cargo test --workspace"
    fi

    if [ "$OPEN_PR" = true ]; then
        branch="chore/update-fastembed-models-$(date +%Y%m%d)"
        git checkout -b "$branch"
        git add "$REGISTRY_FILE" "$CARGO_TOML"
        git commit -m "chore: update fastembed model registry (${latest_version})"
        git push -u origin "$branch"
        gh pr create \
            --title "chore: update fastembed model registry" \
            --body "Auto-generated by scripts/update-local-models.sh

- Current fastembed: ${current_version}
- Latest fastembed: ${latest_version}
- Registry models: ${model_count}

Review new models and add to registry if appropriate."
        echo "PR created."
    fi
fi
