#!/usr/bin/env bash
set -euo pipefail

# ╔══════════════════════════════════════════════════════════════════════╗
# ║  Update API Models Registry                                         ║
# ║  Checks API providers for new embedding models.                     ║
# ╚══════════════════════════════════════════════════════════════════════╝
#
# Usage:
#   bash scripts/update-api-models.sh          # check only (dry run)
#   bash scripts/update-api-models.sh --apply  # apply timestamp update
#   bash scripts/update-api-models.sh --pr     # apply + open PR

APPLY=false
OPEN_PR=false
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGISTRY_FILE="${REPO_ROOT}/models/api-models.toml"

for arg in "$@"; do
    case "$arg" in
        --apply) APPLY=true ;;
        --pr) APPLY=true; OPEN_PR=true ;;
        --help) echo "Usage: $0 [--apply] [--pr]"; exit 0 ;;
    esac
done

echo "═══ API Models Registry Update ═══"
echo ""

# ── Step 1: List current registry ──────────────────────────────────────
echo "Current API providers and models:"
echo ""
grep -E '^\[providers\.' "$REGISTRY_FILE" | while read -r line; do
    key=$(echo "$line" | sed 's/\[\(.*\)\]/\1/')
    depth=$(echo "$key" | tr -cd '.' | wc -c)
    if [ "$depth" -eq 1 ]; then
        echo "  Provider: $(echo "$key" | sed 's/providers\.//')"
    elif echo "$key" | grep -q 'models\.'; then
        model=$(echo "$key" | sed 's/.*models\.//')
        echo "    - ${model}"
    fi
done

echo ""

# ── Step 2: Check OpenAI ──────────────────────────────────────────────
echo "Checking OpenAI models..."
if command -v curl &>/dev/null && [ -n "${OPENAI_API_KEY:-}" ]; then
    openai_models=$(curl -sL "https://api.openai.com/v1/models" \
        -H "Authorization: Bearer ${OPENAI_API_KEY}" 2>/dev/null || echo "")
    if [ -n "$openai_models" ]; then
        echo "  OpenAI embedding models available:"
        echo "$openai_models" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for m in sorted(data.get('data', []), key=lambda x: x['id']):
    if 'embed' in m['id'].lower():
        print(f\"    - {m['id']}\")
" 2>/dev/null || echo "    (could not parse response)"
    else
        echo "  Could not reach OpenAI API (set OPENAI_API_KEY to check)"
    fi
else
    echo "  Skipped (no OPENAI_API_KEY set)"
fi

echo ""

# ── Step 3: Check Voyage ──────────────────────────────────────────────
echo "Checking Voyage AI docs..."
echo "  Manual check: https://docs.voyageai.com/docs/embeddings"
echo "  Current registry models: voyage-3, voyage-3-lite"

echo ""

# ── Step 4: Check Cohere ──────────────────────────────────────────────
echo "Checking Cohere docs..."
echo "  Manual check: https://docs.cohere.com/reference/embed"
echo "  Current registry models: embed-v4.0, embed-multilingual-v3.0"

echo ""

# ── Step 5: Report ─────────────────────────────────────────────────────
echo "═══ Action Items ═══"
echo "1. Check each provider's docs for new models"
echo "2. Add new models to models/api-models.toml"
echo "3. Run: cargo test -p the-one-memory models_registry"
echo "4. Mark deprecated models (do NOT remove)"

if [ "$APPLY" = true ]; then
    echo ""
    echo "═══ Applying Changes ═══"
    sed -i "s/^updated = .*/updated = \"$(date +%Y-%m-%d)\"/" "$REGISTRY_FILE"
    echo "Updated registry timestamp."

    if [ "$OPEN_PR" = true ]; then
        branch="chore/update-api-models-$(date +%Y%m%d)"
        git checkout -b "$branch"
        git add "$REGISTRY_FILE"
        git commit -m "chore: update API model registry"
        git push -u origin "$branch"
        gh pr create \
            --title "chore: update API model registry" \
            --body "Auto-generated by scripts/update-api-models.sh

Review new models and add to registry if appropriate."
        echo "PR created."
    fi
fi
